#
#   DockerFile to create images for GAEP. This creates a development environment for GAEP.
#   Images installs
#    - pip
#
#
FROM google/cloud-sdk

# Build variables
ENV FILEBEAT_VERSION=1.0.05

# Command to install pip (did not find this in the cloud-sdk image) :
#	https://pip.pypa.io/en/stable/installing/


#download curl, Download and install filebeats
RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py
